<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'AjaxController' => $baseDir . '/app/controllers/AjaxController.php',
    'Aula' => $baseDir . '/app/models/Aula.php',
    'AuthController' => $baseDir . '/app/controllers/AuthController.php',
    'BaseController' => $baseDir . '/app/controllers/BaseController.php',
    'CrudController' => $baseDir . '/app/controllers/CrudController.php',
    'DatabaseSeeder' => $baseDir . '/app/database/seeds/DatabaseSeeder.php',
    'Disponible' => $baseDir . '/app/models/Disponible.php',
    'Hora' => $baseDir . '/app/models/Hora.php',
    'Horario' => $baseDir . '/app/models/Horario.php',
    'IlluminateQueueClosure' => $vendorDir . '/laravel/framework/src/Illuminate/Queue/IlluminateQueueClosure.php',
    'Plan' => $baseDir . '/app/models/Plan.php',
    'Plantilla' => $baseDir . '/app/models/Plantilla.php',
    'Professor' => $baseDir . '/app/models/Professor.php',
    'Proyecto' => $baseDir . '/app/models/Proyecto.php',
    'ProyectosController' => $baseDir . '/app/controllers/ProyectosController.php',
    'SessionHandlerInterface' => $vendorDir . '/symfony/http-foundation/Symfony/Component/HttpFoundation/Resources/stubs/SessionHandlerInterface.php',
    'Subject' => $baseDir . '/app/models/Subject.php',
    'Symfony\\Component\\HttpFoundation\\Resources\\stubs\\FakeFile' => $vendorDir . '/symfony/http-foundation/Symfony/Component/HttpFoundation/Resources/stubs/FakeFile.php',
    'TestCase' => $baseDir . '/app/tests/TestCase.php',
    'User' => $baseDir . '/app/models/User.php',
);
